name: Restrict Direct PRs to Master

on:
  pull_request:
    branches:
      - master

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Source Branch
        run: |
          SOURCE_BRANCH="${{ github.head_ref }}"
          TARGET_BRANCH="${{ github.base_ref }}"

          # Allow PRs to master **only** from feature-release/*
          if [[ "$TARGET_BRANCH" == "master" && ! "$SOURCE_BRANCH" =~ ^feature-release/ ]]; then
            echo "❌ ERROR: You can only open PRs to 'master' from 'feature-release/*' branches!"
            exit 1
          fi

          # Prevent PRs from master to any branch
          if [[ "$SOURCE_BRANCH" == "master" ]]; then
            echo "❌ ERROR: You cannot open PRs from the 'master' branch!"
            exit 1
          fi
